### ISSUE TITLE
Not a real issue, just an enhanced fork to inform you about.

### ISSUE THREAD

**Issue by wize-wiz** [signifly/laravel-database-refactors#5]
First of all, thanks for all the good work with this simple but powerful package.

I was battling with database refactoring for quite some time and luckily found this package that gave me some ideas. The only problem I had was that the "refactoring" process I'm battling with not just deals with upward migration, but also downward (rollbacks). Creating multiple refactor classes for upward and downward refactoring just didn't feel right.

Long story short, I created a [fork](https://github.com/wize-wiz/laravel-database-refactors) and enhanced some parts, ultimately synchronising a refactor class with a migration file without the need of calling the refactor class in the `up` or `down` method of the migration class.

All features are explained in the readme and if by chance this is of interest to you, I could PR the whole thing (with modifications whatsoever). There is still some little work to be done but nothing spooky.

If not, close this issue if you like and I will ask you kindly if I could release it as a new separate package with all licenses and credits attached to.

Cheers.

**Comment by hindermyertim** [comment]
This is nice, I haven't used it, but a lot of the features here are things I've thought about doing for a project I'm working on.

**Comment by emilhorlyck** [comment]
Hey @wize-wiz thanks for the effort. For now I will close this.
